"use client";

import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { EmptyState } from '@/components/ui/EmptyState';
import { AlertBanner } from '@/components/ui/AlertBanner';
import { ResultCard } from '@/components/calculadoras/ResultCard';
import { CalculatorShell } from '@/components/calculadoras/CalculatorShell';

export default function VacationCalculatorPage() {
  const [form, setForm] = useState({ salary: '', months: '', usedDays: '0' }); const [result, setResult] = useState(null); const [error, setError] = useState('');
  const calculate = (event) => { event.preventDefault(); const salary = Number(form.salary); const months = Number(form.months); const usedDays = Number(form.usedDays) || 0; if (salary <= 0 || months < 0 || months > 12 || usedDays < 0) { setError('Revisa sueldo, meses trabajados y días utilizados.'); setResult(null); return; } setError(''); const accrued = months * 1.25; const available = Math.max(0, accrued - usedDays); setResult({ accrued, available, amount: (salary / 30) * available }); };
  return <CalculatorShell title="Calculadora de vacaciones" description="Estima el feriado proporcional según meses trabajados y días utilizados."><div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_380px]"><form onSubmit={calculate} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-medium text-slate-700">Sueldo mensual<input value={form.salary} onChange={(event) => setForm((current) => ({ ...current, salary: event.target.value }))} type="number" min="0" className="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5" /></label><label className="text-sm font-medium text-slate-700">Meses trabajados<input value={form.months} onChange={(event) => setForm((current) => ({ ...current, months: event.target.value }))} type="number" min="0" max="12" step="0.1" className="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5" /></label></div><label className="mt-5 block text-sm font-medium text-slate-700">Días ya utilizados<input value={form.usedDays} onChange={(event) => setForm((current) => ({ ...current, usedDays: event.target.value }))} type="number" min="0" step="0.01" className="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5" /></label>{error ? <div className="mt-5"><AlertBanner tone="error" title="Datos inválidos" description={error} /></div> : null}<Button type="submit" className="mt-6">Calcular vacaciones</Button></form>{result ? <ResultCard title="Días disponibles" value={`${result.available.toFixed(2)} días`} subtitle={`Compensación estimada: $${Math.round(result.amount).toLocaleString('es-CL')} CLP`} rows={[{ label: 'Días devengados', value: `${result.accrued.toFixed(2)} días` }, { label: 'Días utilizados', value: `${form.usedDays} días` }]} /> : <EmptyState title="Aún no hay un resultado" description="Ingresa tus meses trabajados y sueldo mensual." />}</div></CalculatorShell>;
}