"use client";

import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { EmptyState } from '@/components/ui/EmptyState';
import { AlertBanner } from '@/components/ui/AlertBanner';
import { ResultCard } from '@/components/calculadoras/ResultCard';
import { CalculatorShell } from '@/components/calculadoras/CalculatorShell';

export default function OvertimeCalculatorPage() {
  const [form, setForm] = useState({ salary: '', weeklyHours: '44', extraHours: '' }); const [result, setResult] = useState(null); const [error, setError] = useState('');
  const calculate = (event) => { event.preventDefault(); const salary = Number(form.salary); const weeklyHours = Number(form.weeklyHours); const extraHours = Number(form.extraHours); if (salary <= 0 || weeklyHours <= 0 || extraHours < 0) { setError('Ingresa sueldo, jornada y horas extra válidos.'); setResult(null); return; } setError(''); const ordinaryHour = salary / 30 / (weeklyHours / 6); setResult({ ordinaryHour, extraValue: ordinaryHour * 1.5, total: ordinaryHour * 1.5 * extraHours }); };
  return <CalculatorShell title="Calculadora de horas extra" description="Estima el valor de horas extraordinarias con un recargo referencial de 50%."><div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_380px]"><form onSubmit={calculate} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-medium text-slate-700">Sueldo mensual<input value={form.salary} onChange={(event) => setForm((current) => ({ ...current, salary: event.target.value }))} type="number" min="0" className="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5" /></label><label className="text-sm font-medium text-slate-700">Jornada semanal<input value={form.weeklyHours} onChange={(event) => setForm((current) => ({ ...current, weeklyHours: event.target.value }))} type="number" min="1" max="60" className="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5" /></label></div><label className="mt-5 block text-sm font-medium text-slate-700">Cantidad de horas extra<input value={form.extraHours} onChange={(event) => setForm((current) => ({ ...current, extraHours: event.target.value }))} type="number" min="0" step="0.25" className="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5" /></label>{error ? <div className="mt-5"><AlertBanner tone="error" title="Datos inválidos" description={error} /></div> : null}<Button type="submit" className="mt-6">Calcular horas extra</Button></form>{result ? <ResultCard title="Total horas extra" value={`$${Math.round(result.total).toLocaleString('es-CL')} CLP`} subtitle={`${form.extraHours} hora(s) con recargo`} rows={[{ label: 'Valor hora ordinaria', value: `$${Math.round(result.ordinaryHour).toLocaleString('es-CL')} CLP` }, { label: 'Valor hora extraordinaria', value: `$${Math.round(result.extraValue).toLocaleString('es-CL')} CLP` }]} /> : <EmptyState title="Aún no hay un resultado" description="Ingresa tu jornada y cantidad de horas extra." />}</div></CalculatorShell>;
}