"use client";

import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { EmptyState } from '@/components/ui/EmptyState';
import { AlertBanner } from '@/components/ui/AlertBanner';
import { ResultCard } from '@/components/calculadoras/ResultCard';
import { ValidationFlags } from '@/components/calculadoras/ValidationFlags';
import { CalculatorShell } from '@/components/calculadoras/CalculatorShell';

const money = (value) => `$${Math.round(value).toLocaleString('es-CL')} CLP`;

export default function SeveranceCalculatorPage() {
  const [form, setForm] = useState({ salary: '', startDate: '', endDate: '', vacationDays: '', pendingSalary: '0' });
  const [result, setResult] = useState(null); const [flags, setFlags] = useState([]); const [error, setError] = useState('');
  const update = (field) => (event) => setForm((current) => ({ ...current, [field]: event.target.value }));
  const calculate = (event) => { event.preventDefault(); const salary = Number(form.salary); const vacationDays = Number(form.vacationDays); const pendingSalary = Number(form.pendingSalary) || 0; const start = new Date(form.startDate); const end = new Date(form.endDate); const nextFlags = []; if (!salary || salary <= 0) nextFlags.push({ type: 'error', message: 'El sueldo base debe ser mayor que cero.' }); if (!form.startDate || !form.endDate || Number.isNaN(start.getTime()) || Number.isNaN(end.getTime())) nextFlags.push({ type: 'error', message: 'Ingresa ambas fechas de la relación laboral.' }); if (start > end) nextFlags.push({ type: 'error', message: 'La fecha de término no puede ser anterior al inicio.' }); if (vacationDays < 0) nextFlags.push({ type: 'error', message: 'Los días de vacaciones no pueden ser negativos.' }); if (pendingSalary < 0) nextFlags.push({ type: 'warning', message: 'El sueldo pendiente se ajustó a cero.' }); setFlags(nextFlags); setError(''); if (nextFlags.some((flag) => flag.type === 'error')) { setResult(null); return; } const years = Math.max(0, (end - start) / (365.25 * 24 * 60 * 60 * 1000)); const indemnityYears = Math.min(11, Math.floor(years)); const indemnity = salary * indemnityYears; const vacationCompensation = (salary / 30) * vacationDays; setResult({ indemnity, vacationCompensation, pendingSalary: Math.max(0, pendingSalary), total: indemnity + vacationCompensation + Math.max(0, pendingSalary), years, indemnityYears }); };
  return <CalculatorShell title="Calculadora de finiquito" description="Estima indemnizaciones y conceptos pendientes para revisión previa."><div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_380px]"><div className="space-y-6"><form onSubmit={calculate} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-medium text-slate-700">Sueldo base mensual<input value={form.salary} onChange={update('salary')} type="number" min="0" className="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5" /></label><label className="text-sm font-medium text-slate-700">Vacaciones pendientes (días)<input value={form.vacationDays} onChange={update('vacationDays')} type="number" min="0" step="0.01" className="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5" /></label><label className="text-sm font-medium text-slate-700">Fecha de inicio<input value={form.startDate} onChange={update('startDate')} type="date" className="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5" /></label><label className="text-sm font-medium text-slate-700">Fecha de término<input value={form.endDate} onChange={update('endDate')} type="date" className="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5" /></label></div><label className="mt-5 block text-sm font-medium text-slate-700">Remuneración pendiente<input value={form.pendingSalary} onChange={update('pendingSalary')} type="number" min="0" className="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5" /></label>{error ? <div className="mt-5"><AlertBanner tone="error" title="No se pudo calcular" description={error} /></div> : null}<Button type="submit" className="mt-6">Calcular finiquito</Button></form><ValidationFlags flags={flags} /></div>{result ? <ResultCard title="Total estimado" value={money(result.total)} subtitle={`${result.indemnityYears} año(s) considerados para indemnización`} rows={[{ label: 'Indemnización por años de servicio', value: money(result.indemnity) }, { label: 'Feriado proporcional o pendiente', value: money(result.vacationCompensation) }, { label: 'Remuneración pendiente', value: money(result.pendingSalary) }, { label: 'Antigüedad estimada', value: `${result.years.toFixed(1)} años` }]} tone={flags.some((flag) => flag.type === 'error') ? 'error' : 'success'} /> : <EmptyState title="Aún no hay un resultado" description="Completa las fechas y montos para revisar el finiquito." />}</div></CalculatorShell>;
}