"use client";

import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { EmptyState } from '@/components/ui/EmptyState';
import { AlertBanner } from '@/components/ui/AlertBanner';
import { ResultCard } from '@/components/calculadoras/ResultCard';
import { CalculatorShell } from '@/components/calculadoras/CalculatorShell';
import { useEconomicData } from '@/lib/hooks/useEconomicData';

export default function GratificationCalculatorPage() {
  const { indicators } = useEconomicData(); const [form, setForm] = useState({ salary: '', annualProfit: '', workers: '1' }); const [result, setResult] = useState(null); const [error, setError] = useState('');
  const calculate = (event) => { event.preventDefault(); const salary = Number(form.salary); const annualProfit = Number(form.annualProfit); const workers = Number(form.workers); const imm = Number(indicators.imm); if (salary <= 0 || annualProfit < 0 || workers <= 0) { setError('Ingresa valores válidos para sueldo, utilidades y trabajadores.'); setResult(null); return; } const perWorkerMonthly = annualProfit / workers / 12 * 0.25; const legalCap = imm ? (imm * 4.75) / 12 : Infinity; setError(''); setResult({ amount: Math.min(perWorkerMonthly, legalCap), uncapped: perWorkerMonthly, cap: legalCap }); };
  return <CalculatorShell title="Calculadora de gratificación" description="Estima el pago mensual referencial bajo el esquema proporcional de utilidades."><div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_380px]"><form onSubmit={calculate} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-medium text-slate-700">Sueldo mensual<input value={form.salary} onChange={(event) => setForm((current) => ({ ...current, salary: event.target.value }))} type="number" min="0" className="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5" /></label><label className="text-sm font-medium text-slate-700">Utilidad anual de la empresa<input value={form.annualProfit} onChange={(event) => setForm((current) => ({ ...current, annualProfit: event.target.value }))} type="number" min="0" className="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5" /></label></div><label className="mt-5 block text-sm font-medium text-slate-700">Número de trabajadores<input value={form.workers} onChange={(event) => setForm((current) => ({ ...current, workers: event.target.value }))} type="number" min="1" className="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5" /></label>{error ? <div className="mt-5"><AlertBanner tone="error" title="Datos inválidos" description={error} /></div> : null}<Button type="submit" className="mt-6">Calcular gratificación</Button></form>{result ? <ResultCard title="Gratificación mensual estimada" value={`$${Math.round(result.amount).toLocaleString('es-CL')} CLP`} subtitle="Resultado referencial sujeto a revisión legal" rows={[{ label: 'Cálculo proporcional sin tope', value: `$${Math.round(result.uncapped).toLocaleString('es-CL')} CLP` }, { label: 'Tope mensual aplicado', value: Number.isFinite(result.cap) ? `$${Math.round(result.cap).toLocaleString('es-CL')} CLP` : 'Indicador IMM no disponible' }]} /> : <EmptyState title="Aún no hay un resultado" description="Completa los datos de utilidades para estimar la gratificación." />}</div></CalculatorShell>;
}